main = ".open-next/worker.js"

compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]
[assets]
directory = ".open-next/assets"
binding = "ASSETS"


# Enable Workers Logs
[observability]
enabled = true
head_sampling_rate = 100


[env.staging]
name = "staging-app"
routes = [
  { pattern = "staging.runagent.live/*", zone_name = "runagent.live" }
]

[env.prod]
name = "prod-app"
routes = [
  { pattern = "runagent.live/*", zone_name = "runagent.live" }
]