name: Deploy to Cloudflare

on:
  push:
    branches: [staging, production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.1.0'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - name: Configure pnpm cache
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Deploy to Staging Environment
        if: github.ref == 'refs/heads/staging' && github.event_name == 'push'
        env:
          # Cloudflare credentials (secrets)
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          echo "Creating .env file for deployment..."
          cat > .env << EOF
          DATABASE_URL="${{ secrets.DATABASE_URL }}"
          CLERK_SECRET_KEY="${{ secrets.CLERK_SECRET_KEY }}"
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}"
          NEXT_PUBLIC_URL="${{ vars.NEXT_PUBLIC_URL }}"
          EOF
          
          echo "Deploying to staging..."
          pnpm run deploy:staging
          
          echo "Cleaning up .env file..."
          rm .env
      
      - name: Deploy to Production Environment
        if: github.ref == 'refs/heads/production' && github.event_name == 'push'
        env:
          # Cloudflare credentials (secrets)
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          echo "Creating .env file for deployment..."
          cat > .env << EOF
          DATABASE_URL="${{ secrets.DATABASE_URL }}"
          CLERK_SECRET_KEY="${{ secrets.CLERK_SECRET_KEY }}"
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}"
          NEXT_PUBLIC_URL="${{ vars.NEXT_PUBLIC_URL }}"
          EOF
          
          echo "Deploying to production..."
          pnpm run deploy:prod
          
          echo "Cleaning up .env file..."
          rm .env